[package]
name = "near-pool"
version = "0.1.0-pre.1"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/nearprotocol/nearcore"
homepage = "https://github.com/nearprotocol/nearcore"
description = """
This internal crate provides pool of transactions to be processed by the runtime.
"""

[dependencies]
rand = "0.7"
borsh = "0.8.1"

near-crypto = { path = "../../core/crypto", version = "0.1.0" }
near-primitives = { path = "../../core/primitives", version = "0.1.0-pre.1" }
