[package]
name = "near-metrics"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/nearprotocol/nearcore"
homepage = "https://github.com/nearprotocol/nearcore"
description = """
A fork of the lighthouse_metrics crate used to implement prometheus
"""

[dependencies]
lazy_static = "1.4"
prometheus = "0.11"
log = "0.4"

