[package]
name = "restored-receipts-verifier"
version = "0.1.0"
authors = ["Aleksandr Logunov <alex.logunov@near.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.54"
